# -*- mode: ruby -*-
# vi: set ft=ruby :

required_plugins = %w( landrush )
required_plugins.each do |plugin|
      system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end


Vagrant.configure("2") do |config|
  config.vm.box = 'hashicorp/precise64'

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', 2048]
  end

  config.vm.hostname = 'shibboleth.vagrant.dev'
  config.vm.network :private_network, ip: '192.168.66.10'

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "puppet/modules"
  end

  config.landrush.host 'lvh.me', '10.0.2.2' # This is to route traffic to host machine of the VM.
  config.landrush.enable
end
