# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9873a95c2519e7f1d17b972f714762e84911b77f1b28481fb91c3d42efb50ef30c5235197cdc845c7d028e9463a4f2475b2dc67bc3347a146308ec33f18de846

test:
  secret_key_base: e3e6d413ba57dbe5b8bf5d10760bdfe984714851cb04d52dee00d2799e92fc079a6fb672d86b85e84e45dc1d6290811d8e5a97171a1334dd39ee19bf24d0d899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
